### ISSUE TITLE
Problem with load sphere image

### ISSUE THREAD

**Issue by eamanu** [SamHasler/sphere#1]
When I try to load the page I take this menssage:

_Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data._

**Comment by SamHasler** [comment]
Sorry I didn't get to this. Out of interest, which browser was this in? It works for me in Chrome and IE11.

**Comment by eamanu** [comment]
The problem was that sphere doesn't work without a web server.

I put the Sample in a web server and then work

Thanks
